name: enshan-checkin
on:
  schedule:
  - cron: 0 4 * * *
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: |
          pip3 install -r ./requirements.txt
      #- name: Run checkin
        #run: |
          #time=$(($RANDOM%300));echo $time
          #sleep $time
          #python3 ./main.py --token_string "${{ secrets.TOKEN }}"
        #env:
          #PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          #SERVERCHAN_SENDKEY: ${{ secrets.SCKEY }}
          # WECOM_TOKENS: ${{ secrets.WECOM_TOKENS }}
          # WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
          # BARK_DEVICEKEY: ${{ secrets.BARK_DEVICEKEY }}
          # FEISHU_DEVICEKEY: ${{ secrets.FEISHU_DEVICEKEY }}
          
      - name: Run enshan
        run: |
          python3 ./enshan.py
        env:
          ENSHANCK: ${{ secrets.ENSHANCK }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          
      - name: download gao
        run: |
          wget "https://github.com/gaotianliuyun/gao/archive/refs/heads/master.zip"
          unzip master.zip
          tar -czf master.tar.gz gao-master/
          rm -rf ./master.zip ./gao-master/
          git config --local user.email "${{ secrets.EMAIL }}"
          git config --local user.name "${{ github.actor }}"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git status
          git add "master.tar.gz"
          git commit -m "Update master.tar.gz"

      # - name: CN IP4
      #   run: |
      #      python3 ./ip4.py
      #      git config --local user.email "${{ secrets.EMAIL }}"
      #      git config --local user.name "${{ github.actor }}"
      #      git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      #      git status
      #      git add "国内城市IP.csv"
      #      git commit -m "Update 国内城市IP.csv"
      #      git add "ip_ranges.csv"
      #      git commit -m "Update ip_ranges.csv"
      #      git add "cidr_ip.csv"
      #      git commit -m "Update cidr_ip.csv"
      #      git push
      - uses: gautamkrishnar/keepalive-workflow@master
