name: enshan-checkin
on:
  schedule:
  - cron: 0 4 * * *
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: |
          pip3 install -r ./requirements.txt
      #- name: Run checkin
        #run: |
          #time=$(($RANDOM%300));echo $time
          #sleep $time
          #python3 ./main.py --token_string "${{ secrets.TOKEN }}"
        #env:
          #PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          #SERVERCHAN_SENDKEY: ${{ secrets.SCKEY }}
          # WECOM_TOKENS: ${{ secrets.WECOM_TOKENS }}
          # WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
          # BARK_DEVICEKEY: ${{ secrets.BARK_DEVICEKEY }}
          # FEISHU_DEVICEKEY: ${{ secrets.FEISHU_DEVICEKEY }}
          
      - name: Run enshan
        run: |
          python3 ./enshan.py
        env:
          ENSHANCK: ${{ secrets.ENSHANCK }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          
      - name: Watch huggingface
        run: |
          ref=$(curl 'https://huggingface.co/spaces/kinshupoon/test')
          respone=$(echo $ref | grep -o "Running")
          title=huggingface项目状况通知 #发送的标题
          url=http://www.pushplus.plus/send/${{ secrets.PUSHPLUS_TOKEN }}  #请将token字段替换成自己的token          
          if [ "$respone" != "Running" ]; then
              echo "项目已停止"
              content="项目已停止，请登录检查" #发送的内容
              json="{\"token\":  \"${{ secrets.PUSHPLUS_TOKEN }}\", \"title\": \"$title\", \"content\": \"$content\", \"template\": \"html\"}"
              curl -H "Content-Type: application/json" -X POST -d "$json" $url              
          else
              echo "项目运行中"     
          fi
          
      # - name: CN IP4
      #   run: |
      #      python3 ./ip4.py
      #      git config --local user.email "${{ secrets.EMAIL }}"
      #      git config --local user.name "${{ github.actor }}"
      #      git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      #      git status
      #      git add "国内城市IP.csv"
      #      git commit -m "Update 国内城市IP.csv"
      #      git add "ip_ranges.csv"
      #      git commit -m "Update ip_ranges.csv"
      #      git add "cidr_ip.csv"
      #      git commit -m "Update cidr_ip.csv"
      #      git push
      - uses: gautamkrishnar/keepalive-workflow@master
